/**
 * Parses Maestro's debug artifacts (commands JSON, AI report) into structured data.
 * These files are generated by Maestro in ~/.maestro/tests/<timestamp>/
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { MaestroDebugReport } from "../maestro/types.js";

interface MaestroCommandEntry {
  command: Record<string, unknown>;
  metadata: {
    status: "COMPLETED" | "FAILED" | "SKIPPED";
    timestamp: number;
    duration: number;
    error?: {
      message: string;
      hierarchyRoot?: HierarchyNode;
    };
    evaluatedCommand?: Record<string, unknown>;
  };
}

interface HierarchyNode {
  attributes?: Record<string, string>;
  children?: HierarchyNode[];
}

/**
 * Extract a human-readable description from a Maestro command object.
 */
function describeCommand(command: Record<string, unknown>): string {
  const key = Object.keys(command)[0];
  if (!key) return "unknown";

  const value = command[key];

  if (key === "launchAppCommand") {
    const cmd = value as { appId?: string };
    return `launchApp: ${cmd.appId ?? "?"}`;
  }
  if (key === "tapOnElement") {
    const cmd = value as { selector?: { textRegex?: string; idRegex?: string } };
    const target = cmd.selector?.textRegex ?? cmd.selector?.idRegex ?? "?";
    return `tapOn: "${target}"`;
  }
  if (key === "inputTextCommand") {
    const cmd = value as { text?: string };
    return `inputText: "${cmd.text ?? "?"}"`;
  }
  if (key === "assertConditionCommand") {
    return "assertVisible";
  }
  if (key === "swipeCommand") {
    return "swipe";
  }
  if (key === "scrollCommand") {
    return "scroll";
  }
  if (key === "backPressCommand") {
    return "back";
  }
  if (key === "waitForAnimationToEndCommand") {
    return "waitForAnimationToEnd";
  }
  if (key === "takeScreenshotCommand") {
    const cmd = value as { path?: string };
    return `takeScreenshot: ${cmd.path ?? ""}`;
  }
  if (key === "hideKeyboardCommand") {
    return "hideKeyboard";
  }

  return key.replace(/Command$/, "");
}

/**
 * Recursively extract all visible text from a UI hierarchy node.
 * Filters out empty strings and deduplicates.
 */
function extractVisibleTexts(node: HierarchyNode, texts: Set<string> = new Set()): string[] {
  const text = node.attributes?.text;
  if (text && text.trim().length > 0) {
    // Truncate very long texts (like stack traces) to keep output manageable
    texts.add(text.length > 200 ? text.slice(0, 200) + "..." : text);
  }

  if (node.children) {
    for (const child of node.children) {
      extractVisibleTexts(child, texts);
    }
  }

  return Array.from(texts);
}

/**
 * Parse a Maestro commands JSON file into a structured debug report.
 */
export async function parseCommandsJson(debugDir: string): Promise<MaestroDebugReport | null> {
  try {
    // Find commands JSON file — name pattern: commands-(flowname.yaml).json
    const entries = await fs.readdir(debugDir);
    const commandsFile = entries.find((e) => e.startsWith("commands-") && e.endsWith(".json"));
    if (!commandsFile) return null;

    const raw = await fs.readFile(path.join(debugDir, commandsFile), "utf-8");
    const commands: MaestroCommandEntry[] = JSON.parse(raw);

    const completedCommands: string[] = [];
    let failedCommand: MaestroDebugReport["failedCommand"];

    for (const entry of commands) {
      const desc = describeCommand(entry.command);

      if (entry.metadata.status === "COMPLETED") {
        completedCommands.push(desc);
      } else if (entry.metadata.status === "FAILED") {
        const visibleTexts = entry.metadata.error?.hierarchyRoot
          ? extractVisibleTexts(entry.metadata.error.hierarchyRoot)
          : [];

        failedCommand = {
          description: desc,
          error: entry.metadata.error?.message ?? "Unknown error",
          duration: entry.metadata.duration,
          visibleTexts,
        };
      }
    }

    return { completedCommands, failedCommand };
  } catch {
    return null;
  }
}
